version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - java-executor

  java-executor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_executor
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
